// Action Types
export const actionTypes = {
  LOAD_EPISODES_REQUEST: 'LOAD_EPISODES_REQUEST',
  LOAD_EPISODES_SUCCESS: 'LOAD_EPISODES_SUCCESS',
  LOAD_EPISODES_FAILURE: 'LOAD_EPISODES_FAILURE',

  LOAD_SINGLE_EPISODE_REQUEST: 'LOAD_SINGLE_EPISODE_REQUEST',
  LOAD_SINGLE_EPISODE_SUCCESS: 'LOAD_SINGLE_EPISODE_SUCCESS',
  LOAD_SINGLE_EPISODE_FAILURE: 'LOAD_SINGLE_EPISODE_FAILURE',
};
